language: cpp

sudo: required

services:
- docker

python:
  - "3.6"

env:
  global:
    # Doctr deploy key for laristra/wonton
    - secure: "XzgLCdrWTxFiOsPan2UScQ7JWUYXi2RjbwtJB4DvdHe/E5vFZTKl4KoGGD7Q57n0akf80dIpmfu95FsXAbqHdNYeZ1fLyrXK3OwDCAXP6Xk60QCc1CJ4sIiCsL3YMhgQ0cRd+7FGxaJw7ykOAVRIbALbjxDPnNW3Npfb/WkX4NhBNVKf2XNN8RdpSeAJVeGKuWCZmYPO0W04UZaPXvjtpWt9oemvPEbUb0lwDvvgtRzBzK39N1O2QVkjz7HxjhiWBOG5V0vUpXJ7TXD89zQEf8cE66zyKJphbZ2FEGdYvMENt5dII335HqVrOt5TurjxTWM7o6JhUjBqh5IJuEWGwmp5sv5rMsiEE7kMAXv99UANL8GVPj7leg3YM/eL+mHHIHkANGsUaZmOBD99tWSnrFp2admsEa2ZSJkYJpVkmjQBA3lCzw5oNbYeyvVVeo4TtisCiPr0C2TXTi/Z1AnT+g+JYT+HlgJr5BvbW7szgP1mbPzRO1StG/efUI40d4LyCAuiGSzhBRaw+myVvJTOdnPoLolKmTIwWOcGIrpXKkSwPR4+JsRL/PvcbXAqay97f8Ae7qY9Z4f/a+hOtNz0y5ZQyIiYHKv82DQ5IqoQhUIjqhhZ3I1+tLyLLsuL0Mf6fRA6zmvP5yjTXItw51aCKnpvtTsr4lrdD2sJKpxZ46M="
  matrix:
    - MPI=OFF DOCS=true
    - MPI=ON DOCKERHUB=true
    - MPI=ON COVERAGE=ON

script:
  - set -e
  - cp -vr docker ${HOME}/docker
  - cd ../../
  - mv -v ${TRAVIS_REPO_SLUG} $HOME/docker
  - docker build --build-arg MPI=${MPI}
                 --build-arg CI=${CI} --build-arg TRAVIS=${TRAVIS} --build-arg TRAVIS_OS_NAME=${TRAVIS_OS_NAME}
                 --build-arg TRAVIS_BRANCH=${TRAVIS_BRANCH} --build-arg TRAVIS_JOB_NUMBER=${TRAVIS_JOB_NUMBER}
                 --build-arg TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST} --build-arg TRAVIS_JOB_ID=${TRAVIS_JOB_ID}
                 --build-arg TRAVIS_TAG=${TRAVIS_TAG} --build-arg TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG}
                 --build-arg TRAVIS_COMMIT=${TRAVIS_COMMIT} --build-arg COVERAGE=${COVERAGE}
                 --build-arg DOCS=${DOCS}
                 -t ${TRAVIS_REPO_SLUG}:latest ${HOME}/docker/

after_success:
  - if [[ ${DOCKERHUB} = true && ${DOCKER_USERNAME} && ${DOCKER_PASSWORD} && ${TRAVIS_PULL_REQUEST} == false && ${TRAVIS_BRANCH} == master ]]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push "${TRAVIS_REPO_SLUG}:latest";
    fi
  - if [[ ${DOCS} || -n ${TRAVIS_TAG} ]]; then
      cd ${HOME}/docker/wonton;
      CON=$(docker run -d ${TRAVIS_REPO_SLUG}:latest) && docker cp ${CON}:/home/wonton/wonton/build/doc . ;
      pyenv local 3.6;
      pip install git+git://github.com/drdoctr/doctr;
      doctr deploy --built-docs doc/doxygen/html . ;
    fi
