language: cpp

sudo: required

services:
- docker

python:
  - "3.6"

env:
  global:
    # Doctr deploy key for laristra/wonton
    - secure: "pTqSBci9YQPe+B7XkE/OCz8dW9IaZevERK6uJEtDGiwiK1j/w2LNw3NG1+mXFrDA+FLefQYtm2p/iPZj7G8DXoZilTM4GMlbEukNY/gZeduf/G9D4ItY1WPaD7pSkXQ0uYMP5GcMjBSKlRHHmZUxvwZokugmWK3jM6ZVBBpEipvKCzvR7uzA4CdJq7M7JRTJtch+0TtCXBCTOZGT/GHZELXJquzaWgFyBMnWRFzvg0o0rIpTIGKkU0q15NxJ0VLcBcuVFOnNfWvLUX+BNIrYqFVgeCYgojGZatiJhEDktWmq0/J6LCs0gZO9x95PgSCEKnTpXmUR7PdINgiyE1tc42ejnXj66KVVfzwmyyt0lejWGRoLZRKP7Wk2/qcOGvprgo30LO6OJZOl0OXlrRYhipgIIS3nDN6mJ8cvO4nBCOenZRDPIkfa/bUN2q6vZnhmwuSYBpkevqlX29otcij7+Fhk8X62OeGW4rd1VzrsvseAK0RXOTHc5Rwa2V3E/wBysy2UnvmzgxrIEhYELrPdlWgw6FImpy3ggR5Ue1QbeXtQIjbM4KKYMmSXuQefq27jUczYp9OmG9/alKKcpa7Uk7Ypyg53Vsc6TkacArgJckIVmfUatTkHkYjNDza4920OBSY2ip57vzGTiyv03yP2gIRMDx2zE1WYaJOX1lXE6BY="
  matrix:
    - MPI=OFF DOCS=true
    - MPI=ON DOCKERHUB=true
    - MPI=ON COVERAGE=ON

script:
  - set -e
  - cp -vr docker ${HOME}/docker
  - cd ../../
  - mv -v ${TRAVIS_REPO_SLUG} $HOME/docker
  - docker build --build-arg MPI=${MPI}
                 --build-arg CI=${CI} --build-arg TRAVIS=${TRAVIS} --build-arg TRAVIS_OS_NAME=${TRAVIS_OS_NAME}
                 --build-arg TRAVIS_BRANCH=${TRAVIS_BRANCH} --build-arg TRAVIS_JOB_NUMBER=${TRAVIS_JOB_NUMBER}
                 --build-arg TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST} --build-arg TRAVIS_JOB_ID=${TRAVIS_JOB_ID}
                 --build-arg TRAVIS_TAG=${TRAVIS_TAG} --build-arg TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG}
                 --build-arg TRAVIS_COMMIT=${TRAVIS_COMMIT} --build-arg COVERAGE=${COVERAGE}
                 --build-arg DOCS=${DOCS}
                 -t ${TRAVIS_REPO_SLUG}:latest ${HOME}/docker/

after_success:
  - if [[ ${DOCKERHUB} = true && ${DOCKER_USERNAME} && ${DOCKER_PASSWORD} && ${TRAVIS_PULL_REQUEST} == false && ${TRAVIS_BRANCH} == master ]]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push "${TRAVIS_REPO_SLUG}:latest";
    fi
  - if [[ ${DOCS} || -n ${TRAVIS_TAG} ]]; then
      cd ${HOME}/docker/wonton;
      CON=$(docker run -d ${TRAVIS_REPO_SLUG}:latest) && docker cp ${CON}:/home/wonton/wonton/build/doc . ;
      pyenv local 3.6;
      pip install doctr;
      doctr deploy . --built-docs doc/doxygen/html;
    fi
