language: cpp

sudo: required

services:
- docker

python:
  - "3.6"

env:
  global:
    # Doctr deploy key for laristra/wonton
    - secure: "HGYYZBXE1iSLzlR5xJP7ey9keynTjO985EZ8XM9jTA36OKiPfl3QSr3Mci6PTARNpAb5RMVyAMy0lH/0tLKydhZh9uOznf+S3thoaBXqMm4QpR7kcgAtDVeRzVnZ7/rrpuJ8BJ8+rwo4+X5v9IU/PV90dC2MQ91lqBLCVJLd7TLrvPYu5DhFyuARJ4hqZCdSSGWcQ9/djdMb0TQEQZDsavajJpyGx/dM1UB+2nHdzRbGvPlEMS6Xg5AGi6Kc7pKIdKWyimdqeU5XRJZ6aw5fjetpW3LvHAaEmCYkozXPuTp2Z0G74HbfvAcDEoAAWrPmNAizEDV2qpuZ5GrR9eda6VXP/Kj+X43KcDaOk3AA4VzkhOfAz9nDAndTQk5TpYCfygx6bfYBiH+akaowvGJ1UofMYR26igFk+DJ3+4bohZqbdWX2jnn5EKwKcHKCt3+qdUVSvFPM1MzGYyDqknQDoNXfNmFULueOhM+YnJ3RnNha9rO0bdg/a3rrMlQosLJU0lLNJNocibBz/bVCifRLUvH6NmH1KGOYvsyKhUxFMmqAot2xFmxZfsQ/bCd6sv/UfKIuUb0+h1d3smFmvpask6KKi9jUcOymjfYAWB5UA1VFPcDg2fDt/YzwMrx/mQ1sidUG2HU8ZNufBdRKBbrOQ9DTKQ8mBStJHDAR01SPIhA="
  matrix:
    - MPI=OFF DOCS=true
    - MPI=ON DOCKERHUB=true
    - MPI=ON COVERAGE=ON

script:
  - set -e
  - cp -vr docker ${HOME}/docker
  - cd ../../
  - mv -v ${TRAVIS_REPO_SLUG} $HOME/docker
  - docker build --build-arg MPI=${MPI}
                 --build-arg CI=${CI} --build-arg TRAVIS=${TRAVIS} --build-arg TRAVIS_OS_NAME=${TRAVIS_OS_NAME}
                 --build-arg TRAVIS_BRANCH=${TRAVIS_BRANCH} --build-arg TRAVIS_JOB_NUMBER=${TRAVIS_JOB_NUMBER}
                 --build-arg TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST} --build-arg TRAVIS_JOB_ID=${TRAVIS_JOB_ID}
                 --build-arg TRAVIS_TAG=${TRAVIS_TAG} --build-arg TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG}
                 --build-arg TRAVIS_COMMIT=${TRAVIS_COMMIT} --build-arg COVERAGE=${COVERAGE}
                 --build-arg DOCS=${DOCS}
                 -t ${TRAVIS_REPO_SLUG}:latest ${HOME}/docker/

after_success:
  - if [[ ${DOCKERHUB} = true && ${DOCKER_USERNAME} && ${DOCKER_PASSWORD} && ${TRAVIS_PULL_REQUEST} == false && ${TRAVIS_BRANCH} == master ]]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push "${TRAVIS_REPO_SLUG}:latest";
    fi
  - if [[ ${DOCS} || -n ${TRAVIS_TAG} ]]; then
      cd ${HOME}/docker/wonton;
      CON=$(docker run -d ${TRAVIS_REPO_SLUG}:latest) && docker cp ${CON}:/home/wonton/wonton/build/doc . ;
      pyenv local 3.6;
      pip install doctr;
      doctr deploy --built-docs doc/doxygen/html . ;
    fi
